### ISSUE TITLE
Novo container não reconhecido quando existe um outro

### ISSUE THREAD

**Issue by Iolch** [srssaulo/moodle-dev-env#5]
Quando vamos criar um novo container, caso haja algum outro container criado, as configurações do mais recente não serão reconhecidas.

Para conseguir utilizar o novo container em meu localhost, foi necessário executar:

`docker-compose -f docker-compose-phpX.Y.yml --build`
`./start X.Y`

**Comment by srssaulo** [comment]
É provável que isso ocorra por conta dos volumes das bases de dado. Fiz uma alteração que batiza o volume para cada projeto diferente. Não sei se resolve.
